---
title: 'Lab 5: Individual Research Project '
author: "Jennifer Bradham"
date: 'Lab: Sept. 25; Presentations Oct. 9; Report due Oct. 11.'
output:
  pdf_document:
    includes:
      in_header: ees3310.sty
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(stringr)

topic_approval_date = ymd("2017-09-27")
due_date = ymd_hms("2017-10-11 09:00:00", tz="America/Chicago")
presentation_due_date = ymd_hms("2017-10-09 14:10:00", tz="America/Chicago")

date_fmt = function(d) {
  strftime(d, format = "%b. %e") %>% str_trim() %>% str_replace_all(" +", " ")
}

time_fmt = function(d) {
  strftime(d, format = "%l:%M %p") %>% str_trim() %>% str_replace_all(" +", " ")
}
```

# Introduction

Lab 5 provides an opportunity to utilize the skills you have learned thus far in lab to explore a research question pertaining to your specific interests. This lab consists of a written lab report in RMarkdown and a presentation to the class. For this project, you will choose a question or idea pertaining to lab 2, lab 3, or lab 4 and explore the topic a deeper. This may consit of exploring the "why" portion of previous questions that only asked you to describe patterns in the data or it may be evaluating relationships between other variables not assesed in prior labs. To answer your question, you may use the any of the data from lab 2, the MODTRAN model, the GEOCARB model, or a combination thereof. Please get your topic approved by either Dr. Gilligan or Ms. Bradham by `r date_fmt(topic_approval_date)`. The final project is **due `r date_fmt(due_date)` at `r time_fmt(due_date)`**.

## Solo or Team Projects

You may choose to do this project individually or with a partner as a team effort. If you work with a partner, you may work together to design the question, obtain and analyze data, and make a team presentation, but we expect each of you to write a separate report and to indicate who did what on the project. This is similar to the requirement at many research journals that co-authored papers include a statement of what each author contributed.

## Choosing a Topic

For undergraduates, we recommend that you choose a topic from one of the exercises that you did in labs #2--4 and think of a new question along the same lines as the questions that exercise asked.
For graduate students, we expect you to try something more ambitious than just simple extensions of the questions from the lab exercises, but it is still fine to take one of the lab exercises as a starting point.

If you want to do something really different than what we have done previously in lab, that is fine. But check with one of us to make sure your plan is appropriate and feasible (we don't want you to bite off more than you can chew).

**Be CrEaTiVe!** Now is the time to really explore parts of the class that you have found interesting and present your findings in a unique, exciting way. 

# Writen Report (Due `r date_fmt(due_date)`)

Your report should be comprehensive, yet not overly verbose. One recommendation for achieving this is to create an outline to organize your thoughts before initializing writing and data analysis. The report needs to include the following components:

* Introduction

    * *Provide background information that frames the problem you are addressing. At the end of the introduction, the reader should understand exactly **what the problem is** that you are addressing and why that problem is **interesting** and **relevant** to the climate system.*
    
* Methods

    * *Describe the methods for answering your question. The methods section should be written such that someone completely unfamiliar with your project could follow your steps and recreate your results.*

    * This section should contain the R code you use to do the analysis:

        + Getting data into R: download from the internet, read it in from files on your computer, run models, etc.

        + Process data to clean it up: use functions like `mutate`, `gather`, `summarize`, etc. to convert the data into a useful form.

        + Analyze data: anything you do to analyze the data, such as generating descriptive statistics like the mean or standard deviation, fitting linear models to get slopes (rates of change), etc.

* Results

    * *Describe the results of your analyses. Include apropriate charts, tables, graphs, and other quantitative representations of data.* 

    * This section should have R code for making graphs, tables, etc.

* Conclusions/Discussion

    * *Discuss the implications for the results you found using data from your results section.*
    
         * Why are these results significant or interesting? 
 
         * What data supports these conclusions? 
 
         * What are the broader implications of these results? 
 
         * From the results that you have found, what are the next steps to take in this line of research? What other questions have arisen as a result of your analyses?

* Works Cited

    * *Include a works cited section to credit the research and thoughts that are not your own. Be sure to use citations throughout your report where necessary.*

    * We will post a separate document that explains how to do citations and bibliographies in RMarkdown.

Final reports are to be pushed to your Lab 5 Github repository _no later than `r time_fmt(due_date)` on `r date_fmt(due_date)`_. **You must push the .Rmd file *and* the knitted PDF** to Github. A portion of your final report grade will reflect effective use of R/RMarkdown/Github, the clarity and succinctness of your writing, visual representations of data, appropriate discussion of results, and insights into future analyses. 

# Presentation (`r date_fmt(presentation_due_date)`)

Presentations will be limited to five minutes per student. Allot approximately 3.5 to 4 minutes for the presentation of your project and approximately 1 minute for questions. 
Team projects will get five minutes for each team member, and we expect you to coordinate so that each member speaks for roughly equal time.

* You can use Powerpoint to make your presentation, or if you are adventurous, you can use RMarkdown to make a presentation. I will post a separate document about how to use
  RMarkdown to make presentation slides.

* A Powerpoint or PDF of your final presentation needs to be pushed to Github _no later than `r time_fmt(presentation_due_date)` on `r date_fmt(presentation_due_date)`_. 
